### ISSUE TITLE
Multiple stream usage causes GC issues

### ISSUE THREAD

**Issue by Sipkab** [sakerbuild/saker.rmi#4]
When multiple streams are used by an RMI variables context, it can cause garbage collection issues, in case when a garbage collection notification arrives earlier than some method result message.

E.g.: Connection with clients A and B.
1. A calls a method on B with a local object L as an argument, and causes a remote object R to be created on B.
2. The method returns R directly, so the method call result should be L.
3. After the method call result is written from B, R is immediately garbage collected.
4. This garbage collection causes a reference release message back to A. This message arrives earlier than the method result in 2.
5. The references of L decreases to 0, therefore L is no longer known by the RMI connection.
6. When reading the method result, L can no longer be found by the RMI connection, causing an exception.

This issue is caused by incorrectly ordered messages of the method result and garbage collection. The garbage collection happens **after** the method result is written, however, the notification about it arrives earlier due to using multiple streams.

Possible solutions are:
1. Using designated streams for each RMI variables context.
2. Adding some sequence number to the protocol.

Solution 1 requires no protocol modification, therefore seems better.

This issue was somewhat reliably reproducable (issue happened in getBack function call):

```
[saker.java.test]Info: Test information: testing.saker.build.tests.rmi.RMIWrapAnnotTest
[saker.java.test]    ----- Std out -----     
[saker.java.test]RMI test with max stream count: 1
[saker.java.test]RMI test with max stream count: 2
[saker.java.test]RMI test with max stream count: 3
[saker.java.test]RMI test with max stream count: 4
[saker.java.test]RMI test with max stream count: 5
[saker.java.test]RMI test with max stream count: 6
[saker.java.test]java.lang.ThreadGroup[name=RMI test group: testing.saker.build.tests.rmi.RMIWrapAnnotTest,maxpri=10]: 
[saker.java.test]
[saker.java.test]    ----- Std err -----     
[saker.java.test]java.lang.AssertionError: Test case failed: testing.saker.build.tests.rmi.RMIWrapAnnotTest
[saker.java.test]Caused by: java.lang.AssertionError: saker.rmi.exception.RMICallFailedException: saker.rmi.exception.RMICallFailedException: Failed to read method result.
[saker.java.test]	at testing.saker.build.tests.rmi.RMIWrapAnnotTest.runVariablesTestImpl(RMIWrapAnnotTest.java:105)
[saker.java.test]	at testing.saker.build.tests.rmi.BaseVariablesRMITestCase.runTestImpl(BaseVariablesRMITestCase.java:30)
[saker.java.test]	at testing.saker.build.tests.rmi.BaseRMITestCase.connectAndRunTest(BaseRMITestCase.java:92)
[saker.java.test]	at saker.util.function.Functionals$SneakyThrowingRunnable.run(Functionals.java:145)
[saker.java.test]	at java.lang.Thread.run(Thread.java:748)
[saker.java.test]	at saker.util.thread.ExceptionThread.runImpl(ExceptionThread.java:164)
[saker.java.test]	at saker.util.thread.ExceptionThread.run(ExceptionThread.java:141)
[saker.java.test]Caused by: saker.rmi.exception.RMICallFailedException: saker.rmi.exception.RMICallFailedException: Failed to read method result.
[saker.java.test]	at saker.rmi.connection.MethodCallFailedResponse.getReturnValue(MethodCallFailedResponse.java:37)
[saker.java.test]	at saker.rmi.connection.RMIStream.callMethod(RMIStream.java:2983)
[saker.java.test]	at saker.rmi.connection.RMIStream.callMethod(RMIStream.java:2968)
[saker.java.test]	at saker.rmi.connection.RMIVariables.invokeRemoteStaticMethod(RMIVariables.java:382)
[saker.java.test]	at saker.rmi.connection.RMIVariables.invokeRemoteStaticMethod(RMIVariables.java:356)
[saker.java.test]	at testing.saker.build.tests.rmi.RMIWrapAnnotTest.runVariablesTestImpl(RMIWrapAnnotTest.java:87)
[saker.java.test]	... 6 more
[saker.java.test]Caused by: saker.rmi.exception.RMICallFailedException: Failed to read method result.
[saker.java.test]	at saker.rmi.connection.RMIStream.handleCommandMethodResult(RMIStream.java:2144)
[saker.java.test]	at saker.rmi.connection.RMIStream.handleCommand(RMIStream.java:2171)
[saker.java.test]	at saker.rmi.connection.RMIStream.runInput(RMIStream.java:2214)
[saker.java.test]	at saker.rmi.connection.RMIConnection.lambda$offerStreamTask$3(RMIConnection.java:832)
[saker.java.test]	at java.lang.Thread.run(Thread.java:748)
[saker.java.test]Caused by: saker.rmi.exception.RMICallFailedException: Remote object not found with id: 1 (released reference)
[saker.java.test]	at saker.rmi.connection.RMIVariables.requireObjectWithLocalId(RMIVariables.java:1045)
[saker.java.test]	at saker.rmi.connection.RMIStream.readRemoteObject(RMIStream.java:1555)
[saker.java.test]	at saker.rmi.connection.RMIStream.lambda$static$12(RMIStream.java:189)
[saker.java.test]	at saker.rmi.connection.RMIStream.readObject(RMIStream.java:1012)
[saker.java.test]	at saker.rmi.connection.RMIStream.handleCommandMethodResult(RMIStream.java:2134)
[saker.java.test]	... 4 more
[saker.java.test]
[saker.java.test]
[saker.java.test]Error: Test failed: testing.saker.build.tests.rmi.RMIWrapAnnotTest (0.544 seconds)
```

**Comment by Sipkab** [comment]
The possible solutions doesn't solve it unfortunately.

As long as there's any remote method call is active, no garbage collection can proceed, because that method call can return any possible remote object.

Maybe the following:
- Use a single stream per RMI variables.
- A GC message can only be processed on the client if all of the preceeding method result commands have been processed.

This will cause long running remote calls to not block garbage collection. If all method result commands are processed before a given GC command, then there is no possibility that an object that should be the method result is garbage collected before it is read.

Special care should be taken, so writing any GC command should be blocked until the method result itself is serialized and sent. This is because if the method result is a complex object, and it gets serialized, but not written to the connection yet, then if GC happens meanwhile for an indirectly referenced object via the method result object, then it could cause the garbage collection on the client before the result is read.

Other aspects of this should also be examined, apart from method result handling. (Like arguments, and etc...)

**Comment by Sipkab** [comment]
This was prematurely closed as writing a GC command during the serialization of another command has not been tested.
